name: Maven Package

on:
  push:
    branches: [ ci ]
#  release:
#    types: [created]

jobs:
  build-docker-image:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create container
        run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=ghcr.io/danitutu/kafka-protobuf-consumer:test

      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ secrets.CI_DOCKER_USERNAME }} --password-stdin

      - name: Docker push
        run: docker push ghcr.io/danitutu/kafka-protobuf-consumer:test