name: Maven Package

on:
  push:
    branches: [ ci ]
#  release:
#    types: [created]

env:
  IMAGE_NAME:

jobs:
  build-docker-image:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 17
#        uses: actions/setup-java@v2
#        with:
#          java-version: '17'
#          distribution: 'temurin'

      - name: Set image name
#        run: VAR=$(echo kafka-protobuf-consumer:${{ github.event.release.tag_name }} | sed 's/v//')
        run: VAR=$(echo kafka-protobuf-consumer:v1.0.1 | sed 's/v//') && echo $VAR

      - name: Show value
        run: echo $VAR

#      - name: Create container
#        run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=ghcr.io/danitutu/$IMAGE_NAME
#
#      - name: Docker login
#        uses: docker/login-action@v1.12.0
#        with:
#          registry: ghcr.io
#          username: ${{ secrets.CI_DOCKER_USERNAME }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Docker push
#        run: docker push ghcr.io/danitutu/$IMAGE_NAME