name: Maven Package

on:
  release:
    types: [created]

jobs:
  build-docker-image:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set image name
        run: echo IMAGE_NAME="kafka-protobuf-consumer:$(echo ${{ github.event.release.tag_name }} | sed 's/v//')" >> $GITHUB_ENV

      - name: Print image name
        run: echo $IMAGE_NAME

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create container
        run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=ghcr.io/danitutu/$IMAGE_NAME

      - name: Docker login
        uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{ secrets.CI_DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker push
        run: docker push ghcr.io/danitutu/$IMAGE_NAME